# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AccountPageForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(817, 594)
        self.widget_2 = QtWidgets.QWidget(Widget)
        self.widget_2.setGeometry(QtCore.QRect(11, 11, 791, 591))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.widget_2)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Menu = QtWidgets.QToolBox(self.widget)
        self.Menu.setMinimumSize(QtCore.QSize(0, 150))
        self.Menu.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(64, 90, 124);")
        self.Menu.setLineWidth(1)
        self.Menu.setObjectName("Menu")
        self.Dropdown = QtWidgets.QWidget()
        self.Dropdown.setGeometry(QtCore.QRect(0, 0, 99, 113))
        self.Dropdown.setObjectName("Dropdown")
        self.widget1 = QtWidgets.QWidget(self.Dropdown)
        self.widget1.setGeometry(QtCore.QRect(0, 0, 82, 107))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.GenPass_Button = QtWidgets.QPushButton(self.widget1)
        self.GenPass_Button.setFocusPolicy(QtCore.Qt.TabFocus)
        self.GenPass_Button.setStyleSheet("background-color: rgb(127, 180, 233);\n"
"")
        self.GenPass_Button.setObjectName("GenPass_Button")
        self.verticalLayout_3.addWidget(self.GenPass_Button)
        self.Nuke_Button = QtWidgets.QPushButton(self.widget1)
        self.Nuke_Button.setStyleSheet("background-color: rgb(127, 180, 233);\n"
"")
        self.Nuke_Button.setObjectName("Nuke_Button")
        self.verticalLayout_3.addWidget(self.Nuke_Button)
        self.Menu.addItem(self.Dropdown, "")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 99, 113))
        self.page.setObjectName("page")
        self.Menu.addItem(self.page, "")
        self.verticalLayout_2.addWidget(self.Menu)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.widget2 = QtWidgets.QWidget(self.splitter)
        self.widget2.setObjectName("widget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.widget3 = QtWidgets.QWidget(self.widget2)
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_2.addWidget(self.widget3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AccountsGridV = QtWidgets.QCheckBox(self.widget2)
        self.AccountsGridV.setChecked(True)
        self.AccountsGridV.setObjectName("AccountsGridV")
        self.horizontalLayout.addWidget(self.AccountsGridV)
        self.AccountVertV = QtWidgets.QCheckBox(self.widget2)
        self.AccountVertV.setObjectName("AccountVertV")
        self.horizontalLayout.addWidget(self.AccountVertV)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.AccountsHolder2 = QtWidgets.QScrollArea(self.widget2)
        self.AccountsHolder2.setWidgetResizable(True)
        self.AccountsHolder2.setObjectName("AccountsHolder2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 659, 236))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.AccountsHolder2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.AccountsHolder2)
        self.AccountsHolder = QtWidgets.QScrollArea(self.widget2)
        self.AccountsHolder.setWidgetResizable(True)
        self.AccountsHolder.setObjectName("AccountsHolder")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 659, 236))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.AccountsHolder.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.AccountsHolder)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.splitter_2)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.gridLayout.addWidget(self.splitter_2, 0, 0, 1, 1)

        self.retranslateUi(Widget)
        self.Menu.setCurrentIndex(0)
        self.Menu.layout().setSpacing(0)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.GenPass_Button.setText(_translate("Widget", "Generate \n"
"Password"))
        self.Nuke_Button.setText(_translate("Widget", "Nuclear \n"
"Option"))
        self.Menu.setItemText(self.Menu.indexOf(self.Dropdown), _translate("Widget", "Menu"))
        self.Menu.setItemText(self.Menu.indexOf(self.page), _translate("Widget", "Close"))
        self.AccountsGridV.setText(_translate("Widget", "Grid Layout"))
        self.AccountVertV.setText(_translate("Widget", "Vertical Layout"))
        self.commandLinkButton.setText(_translate("Widget", "New store account? Click here to add it"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
