# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreateAccountForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(312, 485)
        self.widget = QtWidgets.QWidget(Widget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 319, 491))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.FirstName = QtWidgets.QTextEdit(self.widget)
        self.FirstName.setMaximumSize(QtCore.QSize(16777215, 35))
        self.FirstName.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.FirstName.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.FirstName.setObjectName("FirstName")
        self.verticalLayout.addWidget(self.FirstName)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.LastName = QtWidgets.QTextEdit(self.widget)
        self.LastName.setMaximumSize(QtCore.QSize(16777215, 35))
        self.LastName.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.LastName.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.LastName.setObjectName("LastName")
        self.verticalLayout.addWidget(self.LastName)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.NewEmail = QtWidgets.QTextEdit(self.widget)
        self.NewEmail.setMaximumSize(QtCore.QSize(16777215, 35))
        self.NewEmail.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.NewEmail.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.NewEmail.setObjectName("NewEmail")
        self.verticalLayout.addWidget(self.NewEmail)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.NewUser = QtWidgets.QTextEdit(self.widget)
        self.NewUser.setMaximumSize(QtCore.QSize(16777215, 35))
        self.NewUser.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.NewUser.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.NewUser.setObjectName("NewUser")
        self.verticalLayout.addWidget(self.NewUser)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.NewPassword = QtWidgets.QTextEdit(self.widget)
        self.NewPassword.setMaximumSize(QtCore.QSize(16777215, 35))
        self.NewPassword.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.NewPassword.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.NewPassword.setObjectName("NewPassword")
        self.verticalLayout.addWidget(self.NewPassword)
        self.CreationEnter = QtWidgets.QPushButton(self.widget)
        self.CreationEnter.setStyleSheet("background-color: rgb(127, 180, 233);\n"
"color: rgb(0, 0, 0);")
        self.CreationEnter.setCheckable(False)
        self.CreationEnter.setAutoDefault(True)
        self.CreationEnter.setDefault(True)
        self.CreationEnter.setFlat(False)
        self.CreationEnter.setObjectName("CreationEnter")
        self.verticalLayout.addWidget(self.CreationEnter)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.label_3.setText(_translate("Widget", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:700;\">Create Account</span></p></body></html>"))
        self.label_4.setText(_translate("Widget", "First Name"))
        self.label_5.setText(_translate("Widget", "Last Name"))
        self.label_6.setText(_translate("Widget", "Email"))
        self.label.setText(_translate("Widget", "Username:"))
        self.label_2.setText(_translate("Widget", "Password"))
        self.CreationEnter.setText(_translate("Widget", "Enter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
