# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AccountPageForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(800, 600)
        self.Menu = QtWidgets.QToolBox(Widget)
        self.Menu.setGeometry(QtCore.QRect(20, 10, 85, 181))
        self.Menu.setLineWidth(1)
        self.Menu.setObjectName("Menu")
        self.Dropdown = QtWidgets.QWidget()
        self.Dropdown.setGeometry(QtCore.QRect(0, 0, 85, 125))
        self.Dropdown.setObjectName("Dropdown")
        self.Home_Button = QtWidgets.QPushButton(self.Dropdown)
        self.Home_Button.setGeometry(QtCore.QRect(0, -2, 85, 29))
        self.Home_Button.setStyleSheet("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<ui version=\"4.0\">\n"
" <widget name=\"__qt_fake_top_level\">\n"
"  <widget class=\"QPushButton\" name=\"pushButton_2\">\n"
"   <property name=\"geometry\">\n"
"    <rect>\n"
"     <x>0</x>\n"
"     <y>0</y>\n"
"     <width>85</width>\n"
"     <height>29</height>\n"
"    </rect>\n"
"   </property>\n"
"   <property name=\"text\">\n"
"    <string>PushButton</string>\n"
"   </property>\n"
"  </widget>\n"
" </widget>\n"
" <resources/>\n"
"</ui>\n"
"")
        self.Home_Button.setObjectName("Home_Button")
        self.GenPass_Button = QtWidgets.QPushButton(self.Dropdown)
        self.GenPass_Button.setGeometry(QtCore.QRect(0, 24, 85, 41))
        self.GenPass_Button.setFocusPolicy(QtCore.Qt.TabFocus)
        self.GenPass_Button.setObjectName("GenPass_Button")
        self.Settings_Button = QtWidgets.QPushButton(self.Dropdown)
        self.Settings_Button.setGeometry(QtCore.QRect(0, 62, 85, 29))
        self.Settings_Button.setObjectName("Settings_Button")
        self.Nuke_Button = QtWidgets.QPushButton(self.Dropdown)
        self.Nuke_Button.setGeometry(QtCore.QRect(0, 88, 85, 41))
        self.Nuke_Button.setObjectName("Nuke_Button")
        self.Menu.addItem(self.Dropdown, "")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 85, 125))
        self.page.setObjectName("page")
        self.Menu.addItem(self.page, "")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(Widget)
        self.commandLinkButton.setGeometry(QtCore.QRect(10, 540, 391, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.AccountsHolder = QtWidgets.QScrollArea(Widget)
        self.AccountsHolder.setGeometry(QtCore.QRect(130, 60, 641, 451))
        self.AccountsHolder.setWidgetResizable(True)
        self.AccountsHolder.setObjectName("AccountsHolder")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 639, 449))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.AccountsHolder.setWidget(self.scrollAreaWidgetContents)
        self.AccountsGridV = QtWidgets.QCheckBox(Widget)
        self.AccountsGridV.setGeometry(QtCore.QRect(490, 30, 111, 26))
        self.AccountsGridV.setChecked(True)
        self.AccountsGridV.setObjectName("AccountsGridV")
        self.AccountVertV = QtWidgets.QCheckBox(Widget)
        self.AccountVertV.setGeometry(QtCore.QRect(620, 30, 131, 26))
        self.AccountVertV.setObjectName("AccountVertV")
        self.AccountsHolder2 = QtWidgets.QScrollArea(Widget)
        self.AccountsHolder2.setGeometry(QtCore.QRect(130, 60, 641, 451))
        self.AccountsHolder2.setWidgetResizable(True)
        self.AccountsHolder2.setObjectName("AccountsHolder2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 639, 449))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.AccountsHolder2.setWidget(self.scrollAreaWidgetContents_2)

        self.retranslateUi(Widget)
        self.Menu.setCurrentIndex(1)
        self.Menu.layout().setSpacing(0)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.Home_Button.setText(_translate("Widget", "Home"))
        self.GenPass_Button.setText(_translate("Widget", "Generate \n"
"Password"))
        self.Settings_Button.setText(_translate("Widget", "Settings"))
        self.Nuke_Button.setText(_translate("Widget", "Nuclear \n"
"Option"))
        self.Menu.setItemText(self.Menu.indexOf(self.Dropdown), _translate("Widget", "Menu"))
        self.Menu.setItemText(self.Menu.indexOf(self.page), _translate("Widget", "Close"))
        self.commandLinkButton.setText(_translate("Widget", "New store account? Click here to add it"))
        self.AccountsGridV.setText(_translate("Widget", "Grid Layout"))
        self.AccountVertV.setText(_translate("Widget", "Vertical Layout"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
