# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(800, 600)
        self.CreationEnter = QtWidgets.QPushButton(Widget)
        self.CreationEnter.setGeometry(QtCore.QRect(370, 460, 93, 29))
        self.CreationEnter.setCheckable(False)
        self.CreationEnter.setAutoDefault(True)
        self.CreationEnter.setDefault(True)
        self.CreationEnter.setFlat(False)
        self.CreationEnter.setObjectName("CreationEnter")
        self.CreationEnter.setStyleSheet("border: 2px solid #405A7C;"
        "border-radius: 8px;" "background: #7FB4E9")
        self.NewUser = QtWidgets.QTextEdit(Widget)
        self.NewUser.setGeometry(QtCore.QRect(283, 316, 251, 31))
        self.NewUser.setObjectName("NewUser")
        self.NewUser.setStyleSheet("border: 2px solid #405A7C;"
        "border-radius: 15px;" "background: #FFFFFF")
        self.label = QtWidgets.QLabel(Widget)
        self.label.setGeometry(QtCore.QRect(380, 290, 71, 20))
        self.label.setObjectName("label")
        self.NewPassword = QtWidgets.QTextEdit(Widget)
        self.NewPassword.setGeometry(QtCore.QRect(280, 390, 251, 31))
        self.NewPassword.setObjectName("NewPassword")
        self.NewPassword.setStyleSheet("border: 2px solid #405A7C;"
        "border-radius: 15px;" "background: #FFFFFF")
        self.label_2 = QtWidgets.QLabel(Widget)
        self.label_2.setGeometry(QtCore.QRect(380, 370, 71, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Widget)
        self.label_3.setGeometry(QtCore.QRect(250, 0, 291, 101))
        self.label_3.setObjectName("label_3")
        self.NewEmail = QtWidgets.QTextEdit(Widget)
        self.NewEmail.setGeometry(QtCore.QRect(280, 250, 251, 31))
        self.NewEmail.setObjectName("NewEmail")
        self.NewEmail.setStyleSheet("border: 2px solid #405A7C;"
        "border-radius: 15px;" "background: #FFFFFF")
        self.LastName = QtWidgets.QTextEdit(Widget)
        self.LastName.setGeometry(QtCore.QRect(280, 190, 251, 31))
        self.LastName.setObjectName("LastName")
        self.LastName.setStyleSheet("border: 2px solid #405A7C;"
        "border-radius: 15px;" "background: #FFFFFF")
        self.FirstName = QtWidgets.QTextEdit(Widget)
        self.FirstName.setGeometry(QtCore.QRect(280, 130, 251, 31))
        self.FirstName.setObjectName("FirstName")
        self.FirstName.setStyleSheet("border: 2px solid #405A7C;"
        "border-radius: 15px;" "background: #FFFFFF")
        self.label_4 = QtWidgets.QLabel(Widget)
        self.label_4.setGeometry(QtCore.QRect(380, 100, 81, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Widget)
        self.label_5.setGeometry(QtCore.QRect(380, 170, 81, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Widget)
        self.label_6.setGeometry(QtCore.QRect(390, 230, 63, 20))
        self.label_6.setObjectName("label_6")


        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.CreationEnter.setText(_translate("Widget", "Enter"))
        self.label.setText(_translate("Widget", "Username:"))
        self.label_2.setText(_translate("Widget", "Password"))
        self.label_3.setText(_translate("Widget", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:700;\">Create Account</span></p></body></html>"))
        self.label_4.setText(_translate("Widget", "First Name"))
        self.label_5.setText(_translate("Widget", "Last Name"))
        self.label_6.setText(_translate("Widget", "Email"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
