# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(800, 600)
        self.CreationEnter = QtWidgets.QPushButton(Widget)
        self.CreationEnter.setGeometry(QtCore.QRect(370, 460, 93, 29))
        self.CreationEnter.setCheckable(False)
        self.CreationEnter.setAutoDefault(True)
        self.CreationEnter.setDefault(True)
        self.CreationEnter.setFlat(False)
        self.CreationEnter.setObjectName("CreationEnter")
        self.NewUser = QtWidgets.QTextEdit(Widget)
        self.NewUser.setGeometry(QtCore.QRect(283, 316, 251, 31))
        self.NewUser.setObjectName("NewUser")
        self.label = QtWidgets.QLabel(Widget)
        self.label.setGeometry(QtCore.QRect(380, 290, 71, 20))
        self.label.setObjectName("label")
        self.NewPassword = QtWidgets.QTextEdit(Widget)
        self.NewPassword.setGeometry(QtCore.QRect(280, 390, 251, 31))
        self.NewPassword.setObjectName("NewPassword")
        self.label_2 = QtWidgets.QLabel(Widget)
        self.label_2.setGeometry(QtCore.QRect(380, 370, 71, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Widget)
        self.label_3.setGeometry(QtCore.QRect(270, 170, 291, 101))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.CreationEnter.setText(_translate("Widget", "Enter"))
        self.label.setText(_translate("Widget", "Username:"))
        self.label_2.setText(_translate("Widget", "Password"))
        self.label_3.setText(_translate("Widget", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:700;\">Create Account</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
