# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NukeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        Widget.setFont(font)
        Widget.setStyleSheet("background-color: rgb(194, 173, 174);")
        self.Menu = QtWidgets.QToolBox(Widget)
        self.Menu.setGeometry(QtCore.QRect(40, 20, 85, 171))
        self.Menu.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(64, 90, 124);")
        self.Menu.setLineWidth(1)
        self.Menu.setObjectName("Menu")
        self.Dropdown = QtWidgets.QWidget()
        self.Dropdown.setGeometry(QtCore.QRect(0, 0, 85, 115))
        self.Dropdown.setObjectName("Dropdown")
        self.widget = QtWidgets.QWidget(self.Dropdown)
        self.widget.setGeometry(QtCore.QRect(0, -2, 82, 86))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Home_Button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        self.Home_Button.setFont(font)
        self.Home_Button.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(127, 180, 233);")
        self.Home_Button.setObjectName("Home_Button")
        self.verticalLayout.addWidget(self.Home_Button)
        self.GenPass_Button = QtWidgets.QPushButton(self.widget)
        self.GenPass_Button.setFocusPolicy(QtCore.Qt.TabFocus)
        self.GenPass_Button.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(127, 180, 233);")
        self.GenPass_Button.setObjectName("GenPass_Button")
        self.verticalLayout.addWidget(self.GenPass_Button)
        self.Menu.addItem(self.Dropdown, "")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 85, 115))
        self.page.setObjectName("page")
        self.Menu.addItem(self.page, "")
        self.NUKEBUTTON = QtWidgets.QPushButton(Widget)
        self.NUKEBUTTON.setGeometry(QtCore.QRect(270, 280, 281, 171))
        self.NUKEBUTTON.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(127, 180, 233);")
        self.NUKEBUTTON.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../NukeImage.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NUKEBUTTON.setIcon(icon)
        self.NUKEBUTTON.setIconSize(QtCore.QSize(231, 171))
        self.NUKEBUTTON.setAutoDefault(True)
        self.NUKEBUTTON.setDefault(True)
        self.NUKEBUTTON.setFlat(False)
        self.NUKEBUTTON.setObjectName("NUKEBUTTON")
        self.warningTXT = QtWidgets.QTextEdit(Widget)
        self.warningTXT.setGeometry(QtCore.QRect(210, 140, 411, 121))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        self.warningTXT.setFont(font)
        self.warningTXT.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.warningTXT.setObjectName("warningTXT")

        self.retranslateUi(Widget)
        self.Menu.setCurrentIndex(0)
        self.Menu.layout().setSpacing(0)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.Home_Button.setText(_translate("Widget", "Home"))
        self.GenPass_Button.setText(_translate("Widget", "Generate \n"
"Password"))
        self.Menu.setItemText(self.Menu.indexOf(self.Dropdown), _translate("Widget", "Menu"))
        self.Menu.setItemText(self.Menu.indexOf(self.page), _translate("Widget", "Close"))
        self.warningTXT.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Corbel\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; text-decoration: underline;\">WARNING</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">: </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">This will </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-style:italic; text-decoration: underline;\">PERMANENTLY</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"> delete all of your account information from our database.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">If you wish to continue using Porcupass after pressing this button you will have to</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">make a new account</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
