# -*- coding: utf-8 -*-

# Widget implementation generated from reading ui file 'C:\Users\John\TeamBlue_Porcupass\res\UI Widgets\PassReset.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

#from AccountUI import Ui_Widget, Widget


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(375, 178)
        self.titleLabel = QtWidgets.QLabel(Widget)
        self.titleLabel.setGeometry(QtCore.QRect(90, 20, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(21)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.emailLabel = QtWidgets.QLabel(Widget)
        self.emailLabel.setGeometry(QtCore.QRect(160, 70, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        self.emailLabel.setFont(font)
        self.emailLabel.setObjectName("emailLabel")
        self.ResetEmail = QtWidgets.QTextEdit(Widget)
        self.ResetEmail.setGeometry(QtCore.QRect(70, 100, 231, 31))
        self.ResetEmail.setObjectName("ResetEmail")
        self.ResetEmail.setStyleSheet("border: 2px solid black;"
        "border-radius: 14px;" "background: #FFFFFF")
        self.sendresetButton = QtWidgets.QPushButton(Widget)
        self.sendresetButton.setGeometry(QtCore.QRect(130, 140, 101, 23))
        self.sendresetButton.setObjectName("sendresetButton")
        self.sendresetButton.setStyleSheet("border: 2px solid black;"
        "border-radius: 8px;" "background: #7FB4E9")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.titleLabel.setText(_translate("Widget", "Password Reset"))
        self.emailLabel.setText(_translate("Widget", "Email"))
        self.sendresetButton.setText(_translate("Widget", "Send Reset Email"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    Widget.setStyleSheet("background: #C2ADAE")
    sys.exit(app.exec_())
